
const product_list =  [
    {
        id: 1,
        title: "iPhone 13",
        description: "An apple mobile which is nothing like apple",
        price: 549,
        quantity:1,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "smartphones",
        thumbnail: "https://cdn1.smartprix.com/rx-iHbVjGgm6-w1200-h1200/HbVjGgm6.jpg",
          images: "https://cdn1.smartprix.com/rx-iHbVjGgm6-w1200-h1200/HbVjGgm6.jpg"
    },
    {
        id: 2,
        title: "redmi 13C",
        description: "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
        price: 899,
        quantity:1,
        discountPercentage: 17.94,
        rating: 4.44,
        brand: "Redmi",
        stock: 34,
        category: "smartphones",
        thumbnail: "https://i03.appmifile.com/369_item_in/31/12/2023/538331d5e0ae247b68959bcaf515b2a7.jpg",
        images: "https://i03.appmifile.com/369_item_in/31/12/2023/538331d5e0ae247b68959bcaf515b2a7.jpg"
    },
    {
        id: 3,
        title: "realme 12pro",
        description: "Realme new variant which goes beyond Galaxy to the Universe",
        price: 1249,
        quantity:1,
        discountPercentage: 15.94,
        rating: 4.09,
        stock: 22,
        brand: "Realme",
        category: "smartphones",
        thumbnail: "https://cdn1.smartprix.com/rx-iqDKgfAiw-w420-h420/realme-12-pro-5g.jpg",
        images: "https://cdn1.smartprix.com/rx-iqDKgfAiw-w420-h420/realme-12-pro-5g.jpg"
    },
    {
        id: 4,
        title: "Samsung S21FE",
        description: "Samsung is officially announced on April 2025.",
        price: 280,
        quantity:1,
        discountPercentage: 12.22,
        rating: 3,
        brand: "Samsung",
        stock: 10,
        category: "smartphones",
        thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHqjWAzra58UhobWgDTl3aYzWEnTY2NZcU9A&s",
        images: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHqjWAzra58UhobWgDTl3aYzWEnTY2NZcU9A&s"
    },
    {
        id: 5,
        title: "iphone 15pro",
        description: "An apple mobile which is nothing like apple...",
        price: 499,
        quantity:1,
        discountPercentage: 10.00,
        rating: 3,
        brand: "Apple",
        stock: 23,
        category: "smartphones",
        thumbnail: "https://cdn1.smartprix.com/rx-iHbVjGgm6-w1200-h1200/HbVjGgm6.jpg",
        images: "https://cdn1.smartprix.com/rx-iHbVjGgm6-w1200-h1200/HbVjGgm6.jpg"
    },
    {
        id: 6,
        title: "Vivo v29e",
        description: "Vivo is a perfect selfi camera...",
        price: 450,
        quantity:1,
        discountPercentage: 16.33,
        rating: 4.6,
        brand: "Vivo",
        stock: 20,
        category: "smartphones",
        thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAePEmJYs2cLI1XqGUlK9Q0AIQbUFYYBWtZQ&s",
       images: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAePEmJYs2cLI1XqGUlK9Q0AIQbUFYYBWtZQ&s"
    },
    {
        id: 7,
        title: "iPhone X Pro",
        description: "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
        price: 1099,
        quantity:1,
        discountPercentage: 19.34,
        rating: 4.44,
        brand: "Apple",
        stock: 12,
        category: "smartphones",
        thumbnail: "https://images-cdn.ubuy.co.in/65414af8fd4858736a695a7e-pre-owned-apple-iphone-x-256gb-factory.jpg",
       images: "https://images-cdn.ubuy.co.in/65414af8fd4858736a695a7e-pre-owned-apple-iphone-x-256gb-factory.jpg"
    },
    {
        id: 8,
        title: "realme X",
        description: "realme X new variant which goes beyond Galaxy to the Universe",
        price: 849,
        quantity:1,
        rating: 4.09,
        brand: "Realme",
        category: "smartphones",
      images: "https://static.toiimg.com/thumb/resizemode-4,msid-69140853,imgsize-500,width-800/69140853.jpg"
    },
    {
        id: 9,
        title: "OPPOF19 Pro",
        description: "OPPO F19 is officially announced on April 2021.",
        price: 280,
        quantity:1,
        discountPercentage: 12.34,
        stock: 56,
        rating: 3,
        brand: "OPPO",
        category: "smartphones",
        thumbnail: "https://opsg-img-cdn-gl.heytapimg.com/epb/202401/03/FmsGOwNtafyTY2BK.png",
       images: "https://opsg-img-cdn-gl.heytapimg.com/epb/202401/03/FmsGOwNtafyTY2BK.png"
    },
    {
        id: 10,
        title: "Huawei S6",
        description: "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
        price: 399,
        quantity:1,
        discountPercentage: 13.56,
        rating: 3,
        stock: 45,
        brand: "Huawei",
        category: "smartphones",
        thumbnail: "https://consumer.huawei.com/content/dam/huawei-cbg-site/common/mkt/plp/phones-20230509/view-all-phones/all-y72.png",
        images: "https://consumer.huawei.com/content/dam/huawei-cbg-site/common/mkt/plp/phones-20230509/view-all-phones/all-y72.png"
    },

];



export { product_list};